#  LINH WEB SERVER
##############################################

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
  client:  
    serviceUrl:
      defaultZone: http://localhost:8067/eureka/
     
server:
  port: 1111   
  
  
spring:
  application:
    name: hello-service
  thymeleaf:
    cached: false     
    prefix: classpath:/web-views/